---
title: "PyFlipbook - Merge parameters"
subtitle: "With {flipbookr} and xaringan"
author: "Suraj Thapa and Gina Reynolds, May 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---




```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, 
                      comment = "", cache = F, fig.retina = 3, eval = F)
library(flipbookr)
library(reticulate)
```


---
# Import required packages

`r chunk_reveal("import_packages", lang = "python")`

```{python import_packages, include = T}
import numpy as np
import pandas as pd
from vega_datasets import data
```
---

# Using Merge 
---
### Let's get data ready first
---
`r chunk_reveal("merge1", lang = "python", left_assign=TRUE)`

```{python merge1, include = T}
countries=['China','United States','Argentina','Norway']
df = data.countries()
df.head()
df = df[df.country.isin(countries)]
df = df.reset_index(drop=True)

df.head()

df1 = df.iloc[[24,35], [1,3,8]]
df1 = df1.reset_index(drop=True)
df1

df2 = df.iloc[[5,10,24,25,34,35], [1,6,7]]
df2 = df2.reset_index(drop=True)
df2

```

---
### Parameter *left* & *right*
- left is first dataframe you enter and right is second dataframe you enter
  + right dataframe is object to merge with
  
- Arrange cols will help us to get columns in that order
- Remember left df is first df and right df is second df
  
---
`r chunk_reveal("merge2", lang = "python")`

```{python merge2, include = F}
df1
df2
arrange_cols = ['country','year', 'life_expect', 'p_fertility', 'p_life_expect']
pd.merge(df1,df2)[arrange_cols]
```
---

### Parameter *how* 
- how : {'left', 'right', 'outer', 'inner'}
- outer: use union of keys from both frames, similar to a SQL full outer join; sort keys lexicographically.
- inner: use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys.
- default is 'inner' (see the difference between inner which is `no arguments` vs outer)
---

`r chunk_reveal("merge3", lang = "python")`

```{python merge3, include=F}
#Using parameter : how - inner {default}
df1
df2
pd.merge(df1,df2)
pd.merge(df2,df1)

#Using how parameter : outer
pd.merge(df1,df2, how='outer')
pd.merge(df2,df1, how='outer')
#Keys are ordered in terms of left dataframe
#Again - outer: use union of keys from both frames
```

---
### Parameter *how* {'left', 'right', 'outer', 'inner'}
#### Using left and right
- Right: use only keys from right frame, similar to a SQL right outer join; preserve key order.
- left: use only keys from left frame, similar to a SQL left outer join; preserve key order.
- In other words, it gives you option to keep all rows (and its order) of which dataframe
---

`r chunk_reveal("merge4", lang = "python")`

```{python merge4, include=F}
#Using left
df1
df2

pd.merge(df1,df2, how='left')[arrange_cols]
pd.merge(df2,df1, how='left')[arrange_cols]
#left: use only keys from left frame, preserve key order

#Using right
#left: use only keys from right frame, preserve key order
pd.merge(df1,df2, how='right')[arrange_cols]
pd.merge(df2,df1, how='right')[arrange_cols]

```

---
### Parameter *on*
- on : label or list
- Column or index level names to join on. These must be found in both DataFrames. If on is *None* and not merging on indexes then this defaults to the intersection of the columns in both DataFrames.
- we will focus on columns only for now.
---
`r chunk_reveal("merge5", lang="python")`

```{python merge5, include=F}
df1_i = df.iloc[[24,35], [1,3,8]].reset_index(drop=True)
df1_i

df2 = df.iloc[[5,10,24,25,34,35], [1,6,7,8]].reset_index(drop=True)
df2

#Let's merge using one column vs two columns

#Using one column
pd.merge(df1_i, df2, on=['year'])
#Comments
  #When merged using year, since default is inner 
   #and left dataframe, it merges years of left_df 
   #(i.e. df1_i) with right_df
  #This means it will find all 1975 and 1980 
    #on right_df and keep them as well

#Using two columns
pd.merge(df1_i, df2, on=['year','country'])
# Comment
 #   - This matches both year and country first
  #  - We can use inner (default), outer, left, right as well 
  #depending upon need
```
---

---
`r chunk_reveal("merge6", lang="python", break_type="rotate")`

```{python merge6, width=3, include=F}
#Using *how* parameter with parameter *on*
df1_i
df2

#pd.merge(df1_i, df2, on=['year','country']) #ROTATE

#Now using *how* parameter with parameter *on*
pd.merge(df1_i, df2, on=['year','country'], how="inner") #ROTATE
pd.merge(df1_i, df2, on=['year','country'], how="outer") #ROTATE
pd.merge(df1_i, df2, on=['year','country'], how="left") #ROTATE
pd.merge(df1_i, df2, on=['year','country'], how="right") #ROTATE

```
---
### Parameter *left_on* & *right_on*
- left_on : label or list, or array-like
- Column or index level names to join on in the left DataFrame. Can also be an array or list of arrays of the length of the left DataFrame. These arrays are treated as if they are columns.

- right_on : label or list, or array-like
- Column or index level names to join on in the right DataFrame. Can also be an array or list of arrays of the length of the right DataFrame. These arrays are treated as if they are columns.

- In other words, merge different dataframes with different column names
---

`r chunk_reveal("merge7", lang="python")`

```{python merge7, include=F}
df1

diff_name = df2.rename(columns={'country':'Desh',
                               'year':"Year"}).iloc[0:3,:]
diff_name

#merge on one columns
pd.merge(df1,diff_name, left_on='country', right_on='Desh')

#merge on two columns
pd.merge(df1,diff_name, left_on=['country','year'], right_on=['Desh','Year'])

#arrange columns
arrange_cols = ['country', 'Desh', 'Year','year', 'life_expect',
'p_fertility','p_life_expect']
pd.merge(df1,diff_name, left_on=['country','year'],
right_on=['Desh','Year'])[arrange_cols]

```
---
### Parameter *sort*
- Sort the join keys lexicographically in the result DataFrame. If False, the order of the join keys depends on the join type (how keyword).
- We will see sort while merging using one column and both columns.
- On next slide, we will see for one column.

---

`r chunk_reveal("merge9", lang="python")`

```{python merge9, include=F}
df1 = df.iloc[[24,35], [1,3,6]].reset_index(drop=True)
df1
df2 = df.iloc[[5,10,24,25,34,35], [6,7,8]].reset_index(drop=True)
df2
arrange_cols = ['country', 'year', 'life_expect', 'p_fertility','p_life_expect']

pd.merge(df1,df2, how='outer', sort=False)[arrange_cols]
pd.merge(df1,df2, how='outer', sort=True)[arrange_cols]

```

---
- see the order of country on both sort
---

`r chunk_reveal("merge10", lang="python", break_type="rotate")`

```{python merge10, include=F}
df1 = df.iloc[[24,35], [1,3,6]].reset_index(drop=True)
df1
df2 = df.iloc[[5,10,24,25,34,35], [6,7,8]].reset_index(drop=True)
df2
arrange_cols = ['country', 'year', 'life_expect', 'p_fertility','p_life_expect']

pd.merge(df1,df2, how='outer', sort=False)[arrange_cols] #ROTATE
pd.merge(df1,df2, how='outer', sort=True)[arrange_cols] #ROTATE
```

---
### Parameter *sort* 
- Keep your eyes open for sorting on two columns (year first and then country)

---

`r chunk_reveal("merge11", lang="python")`

```{python merge11, include=F}
df1 = df.iloc[[24,35], [8,1,3,6]].reset_index(drop=True)
df1

df2 = df.iloc[[5,10,24,25,34,35], [8,1,6,7]].reset_index(drop=True)
df2
pd.merge(df2,df1, how='outer')
pd.merge(df2,df1, how='outer', sort=True)

```

---
- country and then year
---

`r chunk_reveal("merge12", lang="python")`

```{python merge12, include=F}
df1 = df.iloc[[24,35], [1,8,3,6]].reset_index(drop=True)
df1

df2 = df.iloc[[5,10,24,25,34,35], [1,8,6,7]].reset_index(drop=True)
df2
pd.merge(df2,df1, how='outer')
pd.merge(df2,df1, how='outer', sort=True)

```
---
### parameter indictor
- If True, adds a column to output DataFrame called “_merge” with information on the source of each row. If string, column with information on source of each row will be added to output DataFrame, and column will be named value of string.

- Information column is Categorical-type and takes on a value of “left_only” for observations whose merge key only appears in ‘left’ DataFrame, “right_only” for observations whose merge key only appears in ‘right’ DataFrame, and “both” if the observation’s merge key is found in both.

---
`r chunk_reveal("merge13", lang="python", break_type="rotate")`

```{python merge13, include=F}
df1 = df.iloc[[24,35], [1,8,3,6]].reset_index(drop=True)
df1

df2 = df.iloc[[5,10,24,25,34,35], [1,8,6,7]].reset_index(drop=True)
df2

pd.merge(df2,df1, how='outer', sort=True, indicator=True) #ROTATE
pd.merge(df2,df1, how='outer', sort=False, indicator=True) #ROTATE
pd.merge(df2,df1, how='inner', sort=True, indicator=True) #ROTATE
pd.merge(df2,df1, how='left', sort=True, indicator=True) #ROTATE
pd.merge(df2,df1, how='right', sort=True, indicator=True) #ROTATE

```
---







```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 50%}
```
