---
title: "A Python Flipbook"
subtitle: "With {flipbookr} and xaringan"
author: "Gina Reynolds, March 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


This is pretty experimental work.  The python "parser" (basically no parsing) means there are strong contraints on code.  Each new line must yeild complete code statement...  


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scracth can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, 
                      comment = "", cache = F, fig.retina = 3, eval = F)
library(flipbookr)
library(tidyverse)
library(reticulate)
```


<!-- This next chunk is just for the developer -- working w/ local code -->

```{r just_for_evamaerey, cache = FALSE, echo = FALSE, eval = T}
try(source("../../../../../R/base_parse_reveal_xaringan.R"))
try(source("../../../../../R/mini.R"))
```


---

`r chunk_reveal("import_packages", lang = "python")`

```{python import_packages, include = F}
import numpy as np
import pandas as pd
```
---

`r chunk_reveal("hello_python", lang = "python")`

```{python hello_python, include=FALSE}
d = [2,3,4]
d
d = ["a","b","c"]
d
```



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 100%}
```
